### ISSUE TITLE
Mac OS build?

### ISSUE THREAD

**Issue by alelordelo** [nihalsid/SRmeetsPS-CUDA#4]
Hey guys, awesome paper!

Is there a Mac OS version coming? : )

**Comment by nihalsid** [comment]
Hi @alelordelo, 

Thanks a lot! Sorry unfortunately we're not planning to work on a mac port for this. But I imagine it won't be much trouble porting it to mac, since we tried to make it cross platform. If you end up trying and run into troubles, feel free to write.

Cheers!
